# Generated by Django 3.1 on 2026-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=64)),
                ('user2', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=155)),
                ('ip_address', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(blank=True, max_length=155, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
    ]
